nginx:
  build: ./nginx
  ports:
    - "3000:80"
  links:
    - "app1:app1"
    - "app2:app2"
    - "app3:app3"

app1:
  build: ./project
  ports:
    - "3000"
  links:
    - "cache:redis"

app2:
  build: ./project
  ports:
    - "3000"
  links:
    - "cache:redis"

app3:
  build: ./project
  ports:
    - "3000"
  links:
    - "cache:redis"

cache:
  image: redis
